name: manius_dungeons
version: '0.1.0-SNAPSHOT'
main: pl.s16.dungeons.ManiusDungeons
api-version: '26.2'
author: S16 SMP 2
softdepend: [BlueMap, WorldGuard, S16Countries]
commands:
  dungeon:
    description: Zarzadzanie manius_dungeons
    usage: /dungeon admin
    aliases: [dungeony]
permissions:
  maniusdungeons.admin:
    description: Dostep do panelu dungeona
    default: op
